export const profiles = [
  {
    name: "LeetCode",
    stat: "200+ Problems",
    logo: "/logos/leetcode.svg",
    link: "#",
    color: "#FFA116",
  },
  {
    name: "GeeksforGeeks",
    stat: "333+ Problems",
    logo: "/logos/geeksforgeeks.svg",
    link: "#",
    color: "#2F8D46",
  },
  {
    name: "GitHub",
    stat: "10+ Repositories",
    logo: "/logos/github.svg",
    link: "#",
    color: "#A855F7",
  },
  {
    name: "TryHackMe",
    stat: "Top 5%",
    logo: "/logos/tryhackme.png",
    link: "#",
    color: "#98E43B",
  },
  {
    name: "CodeChef",
    stat: "Practice",
    logo: "/logos/codechef.svg",
    link: "#",
    color: "#D0A97C",
  },
  {
    name: "HackerRank",
    stat: "Practice",
    logo: "/logos/hackerrank.svg",
    link: "#",
    color: "#2EC866",
  },
  {
    name: "GFG Articles",
    stat: "16+ Articles",
    logo: "/logos/geeksforgeeks.svg",
    link: "#",
    color: "#2F8D46",
  },
];