export const profiles = [
  {
    name: "LeetCode",
    stat: "200+ Problems",
    logo: "/logos/leetcode.svg",
    link: "https://leetcode.com/u/Prasad_Nalla/",
    color: "#FFA116",
  },
  {
    name: "GeeksforGeeks",
    stat: "333+ Problems",
    logo: "/logos/geeksforgeeks.svg",
    link: "https://www.geeksforgeeks.org/profile/nallaprak7hq",
    color: "#2F8D46",
  },
  {
    name: "GitHub",
    stat: "10+ Repositories",
    logo: "/logos/github.svg",
    link: "https://github.com/Prasad-Nalla",
    color: "#A855F7",
  },
  {
    name: "TryHackMe",
    stat: "Top 5%",
    logo: "/logos/tryhackme.png",
    link: "https://tryhackme.com/p/PrasadNalla",
    color: "#98E43B",
  },
  {
    name: "CodeChef",
    stat: "Practice",
    logo: "/logos/codechef.svg",
    link: "https://www.codechef.com/users/prasad_nalla",
    color: "#D0A97C",
  },
  {
    name: "HackerRank",
    stat: "Practice",
    logo: "/logos/hackerrank.svg",
    link: "https://www.hackerrank.com/profile/nallaprasad63631",
    color: "#2EC866",
  },
  {
    name: "GFG Articles",
    stat: "16+ Articles",
    logo: "/logos/geeksforgeeks.svg",
    link: "https://www.geeksforgeeks.org/profile/nallaprak7hq?tab=posts",
    color: "#2F8D46",
  },
];